# 配置文件请严格遵循 yaml 语法格式，yaml 学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

#---------------------------------------环境设置--------------------------------------start
#是否测试环境 0 测试环境 1 线上环境
is_test: 0


#url地址
url:
  test-url: 'http://120.78.198.128:9066/api/AppPush/'
  pro-url: 'http://push-service.mingpinmao.cn/api/AppPush/'
#---------------------------------------环境设置--------------------------------------end


#---------------------------------------项目设置--------------------------------------start

# 0 名品猫项目 1 名品玩家项目
project_type: 0


#---------------------------------------key设置--------------------------------------start

mpm_key:
  header_key:
    - '2901fad4d0de2a4da56ac03093b0ddfc' #测试环境 请求头key
    - 'c89d6bc589af80e26bb44c4b112d87e8' #线上环境 请求头key
  sign_key:
    - 'MjkwMWZhZDRkMGRlMmE0ZGE1NmFjMDMwOTNiMGRkZmM=' #测试环境 验签key
    - 'Yzg5ZDZiYzU4OWFmODBlMjZiYjQ0YzRiMTEyZDg3ZTg=' #正式环境 验签key

mpwj_key:
  header_key:
    - 'f802a6e71315db6e807a8bce21d4a44a' #测试环境 请求头key
    - '91f90e055abe3cbb056a45dfec420610' #线上环境 请求头key
  sign_key:
    - 'ZjgwMmE2ZTcxMzE1ZGI2ZTgwN2E4YmNlMjFkNGE0NGE=' #测试环境 验签key
    - 'OTFmOTBlMDU1YWJlM2NiYjA1NmE0NWRmZWM0MjA2MTA=' #正式环境 验签key

#---------------------------------------key设置--------------------------------------start

#---------------------------------------钉钉token设置------------------------------------------#
dingding_token: 'ab9300b52c6fdb1bd511ce57be6f7e0e3b78ae714ae3ed24795b2c0c67a730d7'